sudo: false
language: rust
matrix:
  include:
  - rust: 1.6.0 # current stable on NixOS 16.03
  - rust: nightly
  - rust: beta
  - rust: stable
script:
- cargo build
- cargo test
- cargo bench
- cargo doc

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

after_success:
 - travis-cargo coveralls --no-sudo --verify
