sudo: false
language: rust
cache: cargo

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls
      - sqlite3
      - libsqlite3-dev

rust:
  - nightly

matrix:
  fast_finish: true

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo install -- diesel_cli --no-default-features --features sqlite --force &&
      diesel migration run &&
      travis-cargo build -- $FEATURES &&
      travis-cargo test -- $FEATURES &&
      travis-cargo --only stable doc -- $FEATURES

after_success: |
  [ $TRAVIS_RUST_VERSION = stable ] &&
  travis-cargo coveralls --no-sudo --verify

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

  matrix:
    - FEATURES=""
