[package]
name = "openfairdb"
version = "0.2.12"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>"]

[dependencies]
r2d2 = "0.8"
clap = "2"
log = "0.3"
slog-envlogger = "2"
uuid = { version = "0.5", features = ["v4"] }
url = "1"
quick-error = "1"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"
serde = "1"
serde_json = "1"
serde_derive = "1"
chrono = "0.4"
lazy_static = "0.2"
regex = "0.2"
pwhash = "0.1"
fast_chemail = "0.9"
quoted_printable = "0.4"
toml = "0.4"
dotenv = "0.10"

r2d2_cypher = { version = "0.4", optional = true }
r2d2-diesel = { version = "1.0.0-beta1", optional = true }
rusted_cypher = { version = "1", optional = true }
diesel = { version = "1.0.0-beta1", features = ["sqlite"], optional = true }
diesel_infer_schema = { version = "1.0.0-beta1", features = ["sqlite"], optional = true }
diesel_migrations = { version = "1.0.0-beta1", features = ["sqlite"], optional = true }
libsqlite3-sys = { version = "0.8", features = ["bundled"], optional = true }

[features]
default = ["neo4j"]
sqlite = ["diesel", "diesel_infer_schema","r2d2-diesel", "libsqlite3-sys", "diesel_migrations"]
neo4j = ["rusted_cypher","r2d2_cypher"]
